<?php

namespace ConnecthysBundle\Repository;

/**
 * ComptesPayeursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptesPayeursRepository extends \Doctrine\ORM\EntityRepository
{
}
