<?php

namespace ConnecthysBundle\Repository;

/**
 * InscriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
