connecthys:
    resource: "@ConnecthysBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@ConnecthysBundle/Controller/"
    type:     annotation

logout:
    path: /logout


