services:
#    connecthys.example:
#        class: ConnecthysBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    ConnecthysBundle.success_handler:
      class: ConnecthysBundle\Service\SuccessHandler
      arguments:
       - '@router'
       - '@security.authorization_checker'
